[package]
name = "encryption_lab2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
web-sys = "0.3"
regex = "1.6"
wasm-logger = "0.2"
log = "0.4"
